dist: trusty
sudo: required
language: java

services:
  - docker

script:
  # https://docs.travis-ci.com/user/docker/
  - docker pull enkeys/alpine-openjdk-amq7-snapshot
  - docker run --rm enkeys/alpine-openjdk-amq7-snapshot &
  - sleep 5
  - mvn clean verify
